import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { calculatePrice, useConsoleStore } from "../../store";
import { api } from "../../api";
import type { InstanceDraft } from "../../domain";
import { Field, Modal, PageHeader } from "../../shared";
import { mapOffering, type InstanceOffering } from "./catalog";

const initialDraft: InstanceDraft = { offeringId: undefined, name: "", region: "", zone: "", billing: "monthly", cpu: 0, memory: 0, gpu: "", image: "", vpcId: "", subnetId: "", privateIp: "", publicIp: false, bandwidth: 0, loginType: "password", password: "", sshKey: "", systemDisk: 40, dataDisk: 0, securityGroupIds: [], resourceGroupId: "", quantity: 1, duration: 1, autoRenew: false, agreement: false };

export function CreateInstancePage() {
  const { state, createInstances, loading } = useConsoleStore(); const navigate = useNavigate(); const location = useLocation();
  const offering = location.state as InstanceOffering | null;
  const [offerings, setOfferings] = useState<InstanceOffering[]>([]);
  const [draft, setDraft] = useState<InstanceDraft>(() => { const base = offering ? { ...initialDraft, offeringId: offering.id, cpu: offering.cpu, memory: offering.memory, gpu: offering.gpu } : initialDraft; const region = state.selectedRegion || state.vpcs[0]?.region || ""; const vpc = state.vpcs.find((item) => item.region === region); const subnet = state.subnets.find((item) => item.vpcId === vpc?.id && item.region === region); const groups = state.securityGroups.filter((item) => item.vpcId === vpc?.id && item.region === region); return { ...base, region, vpcId: vpc?.id || "", subnetId: subnet?.id || "", zone: subnet?.zone || "", securityGroupIds: groups.slice(0, 1).map((item) => item.id) }; });
  const [errors, setErrors] = useState<Record<string, string>>({}); const [confirming, setConfirming] = useState(false);
  useEffect(() => { void Promise.all([api.offerings("cpu"), api.offerings("gpu"), api.offerings("bare_metal")]).then((items) => setOfferings(items.flat().map(mapOffering))).catch(() => setOfferings([])); }, []);
  const price = calculatePrice(draft); const set = <K extends keyof InstanceDraft>(key: K, value: InstanceDraft[K]) => setDraft((d) => ({ ...d, [key]: value }));
  const regionOptions = useMemo(() => [...new Set([
    ...state.vpcs.map((vpc) => vpc.region),
    ...state.subnets.map((subnet) => subnet.region),
    ...state.securityGroups.map((group) => group.region),
    ...state.disks.map((disk) => disk.region),
    ...state.publicIps.map((ip) => ip.region),
    ...state.instances.map((instance) => instance.region),
  ].filter(Boolean))], [state.vpcs, state.subnets, state.securityGroups, state.disks, state.publicIps, state.instances]);
  const vpcOptions = state.vpcs.filter((vpc) => !draft.region || vpc.region === draft.region);
  const subnetOptions = state.subnets.filter((subnet) => subnet.vpcId === draft.vpcId && (!draft.region || subnet.region === draft.region));
  const zoneOptions = [...new Set(subnetOptions.map((subnet) => subnet.zone).filter(Boolean))];
  const securityGroupOptions = state.securityGroups.filter((group) => group.vpcId === draft.vpcId && (!draft.region || group.region === draft.region));
  const validate = () => { const next: Record<string, string> = {}; const selectedSubnet = state.subnets.find((item) => item.id === draft.subnetId); const ipParts = draft.privateIp.split(".").map(Number); const subnetPrefix = selectedSubnet?.cidr.split("/")[0]?.split(".").slice(0, 3).join("."); if (!draft.name.trim()) next.name = "请输入实例名称"; if (!/^[a-zA-Z][a-zA-Z0-9-]{2,31}$/.test(draft.name)) next.name = "以字母开头，仅支持 3-32 位字母、数字和连字符"; if (!draft.region) next.region = "请选择真实区域"; if (!draft.vpcId) next.vpc = "请选择真实 VPC"; if (!draft.image.trim()) next.image = "请输入镜像 ID 或名称"; if (draft.privateIp && (ipParts.length !== 4 || ipParts.some((part) => !Number.isInteger(part) || part < 0 || part > 255))) next.privateIp = "请输入有效的 IPv4 地址"; else if (draft.privateIp && subnetPrefix && !draft.privateIp.startsWith(`${subnetPrefix}.`)) next.privateIp = "私有 IP 必须属于所选子网"; else if (draft.privateIp && state.instances.some((item) => item.privateIp === draft.privateIp)) next.privateIp = "该私有 IP 已被其他实例使用"; if (draft.privateIp && draft.quantity > 1) next.privateIp = "批量创建时请留空，由系统自动分配私有 IP"; if (draft.loginType === "password" && !/^(?=.*[A-Za-z])(?=.*\d).{8,}$/.test(draft.password)) next.password = "至少 8 位，并同时包含字母和数字"; if (draft.loginType === "key" && !draft.sshKey.trim()) next.sshKey = "请输入 SSH 公钥或密钥标识"; if (draft.securityGroupIds.length === 0 || draft.securityGroupIds.some((groupId) => !securityGroupOptions.some((group) => group.id === groupId))) next.securityGroup = "请至少选择一个当前 VPC 的安全组"; if (!draft.agreement) next.agreement = "请先阅读并同意服务协议"; if (!selectedSubnet || selectedSubnet.availableIps < draft.quantity) next.capacity = "所选子网可用 IP 不足"; if (state.balance < price) next.balance = "账户余额不足，请先充值"; setErrors(next); return Object.keys(next).length === 0; };
  const review = () => { if (validate()) setConfirming(true); };
  const submit = async () => { const created = await createInstances(draft); if (created.length === 0) return; setConfirming(false); navigate("/instances", { state: { created: created.map((item) => item.id) } }); };
  return <><PageHeader title="创建云服务器" description="完成计算、网络、存储和安全配置，核对费用后提交。" actions={<button className="button secondary" onClick={() => navigate(-1)}>取消创建</button>} />
    <div className="create-layout"><div className="create-form">
      <ConfigSection title="基础配置" index="01"><div className="form-grid"><Field label="地区" hint={errors.region}><select className={errors.region ? "invalid" : ""} value={draft.region} onChange={(e) => { const region = e.target.value; const vpc = state.vpcs.find((item) => item.region === region); const subnet = state.subnets.find((item) => item.vpcId === vpc?.id && item.region === region); const groups = state.securityGroups.filter((item) => item.vpcId === vpc?.id && item.region === region); setDraft((d) => ({ ...d, region, vpcId: vpc?.id || "", subnetId: subnet?.id || "", zone: subnet?.zone || "", securityGroupIds: groups.slice(0, 1).map((item) => item.id) })); }}><option value="">请选择已同步区域</option>{regionOptions.map((region) => <option key={region}>{region}</option>)}</select></Field><Field label="可用区"><select value={draft.zone} onChange={(e) => set("zone", e.target.value)}><option value="">请选择已同步可用区</option>{zoneOptions.map((zone) => <option key={zone}>{zone}</option>)}</select></Field></div><Field label="计费模式"><div className="segmented"><button className={draft.billing === "hourly" ? "active" : ""} onClick={() => set("billing", "hourly")}>按量计费</button><button className={draft.billing === "monthly" ? "active" : ""} onClick={() => set("billing", "monthly")}>包月</button></div></Field></ConfigSection>
      <ConfigSection title="实例规格" index="02"><div className="choice-grid">{offerings.map((item) => <button key={item.id} className={draft.offeringId === item.id ? "selected" : ""} onClick={() => setDraft((d) => ({ ...d, offeringId: item.id, cpu: item.cpu, memory: item.memory, gpu: item.gpu }))}><strong>{item.name}</strong><span>{item.cpu} vCPU · {item.memory} GB</span><small>{item.gpu}</small></button>)}</div>{offerings.length === 0 && <p className="form-hint">暂无后台实例规格，请先配置产品目录。</p>}{errors.offering && <p className="form-error">{errors.offering}</p>}<Field label="操作系统与镜像" hint={errors.image}><input className={errors.image ? "invalid" : ""} value={draft.image} onChange={(e) => set("image", e.target.value)} placeholder="输入已同步的镜像 ID 或名称" /></Field></ConfigSection>
      <ConfigSection title="网络配置" index="03"><div className="form-grid"><Field label="VPC"><select value={draft.vpcId} onChange={(e) => { const v = e.target.value; const subnet = state.subnets.find((item) => item.vpcId === v && (!draft.region || item.region === draft.region)); setDraft((d) => ({ ...d, vpcId: v, subnetId: subnet?.id ?? "", zone: subnet?.zone ?? "", securityGroupIds: state.securityGroups.filter((group) => group.vpcId === v && (!draft.region || group.region === draft.region)).slice(0, 1).map((group) => group.id) })); }}>{vpcOptions.map((vpc) => <option key={vpc.id} value={vpc.id}>{vpc.name} · {vpc.cidr}</option>)}</select></Field><Field label="子网"><select value={draft.subnetId} onChange={(e) => set("subnetId", e.target.value)}>{subnetOptions.map((subnet) => <option key={subnet.id} value={subnet.id}>{subnet.name} · {subnet.cidr} · 可用 {subnet.availableIps}</option>)}</select></Field><Field label="私有 IP" hint={errors.privateIp || "留空则自动分配"}><input className={errors.privateIp ? "invalid" : ""} placeholder="例如 10.20.1.30" value={draft.privateIp} onChange={(e) => set("privateIp", e.target.value)} /></Field><Field label="公网 IP"><label className="switch-row"><input type="checkbox" checked={draft.publicIp} onChange={(e) => set("publicIp", e.target.checked)} /><span>分配公网 IPv4</span></label></Field>{draft.publicIp && <Field label={`公网带宽 ${draft.bandwidth} Mbps`}><input type="range" min="1" max="200" value={draft.bandwidth} onChange={(e) => set("bandwidth", Number(e.target.value))} /></Field>}</div>{errors.capacity && <p className="form-error">{errors.capacity}</p>}</ConfigSection>
      <ConfigSection title="登录与安全" index="04"><Field label="登录方式"><div className="segmented"><button className={draft.loginType === "password" ? "active" : ""} onClick={() => set("loginType", "password")}>密码</button><button className={draft.loginType === "key" ? "active" : ""} onClick={() => set("loginType", "key")}>SSH 密钥</button></div></Field>{draft.loginType === "password" ? <Field label="登录密码" required hint={errors.password}><input type="password" placeholder="至少 8 位，包含字母和数字" value={draft.password} onChange={(e) => set("password", e.target.value)} className={errors.password ? "invalid" : ""} /></Field> : <Field label="SSH 公钥或密钥标识" hint={errors.sshKey}><input value={draft.sshKey} onChange={(e) => set("sshKey", e.target.value)} placeholder="输入已配置的 SSH 密钥标识" className={errors.sshKey ? "invalid" : ""} /></Field>}<Field label="安全组" hint={errors.securityGroup}><div className="check-list">{securityGroupOptions.map((sg) => <label key={sg.id}><input type="checkbox" checked={draft.securityGroupIds.includes(sg.id)} onChange={(e) => set("securityGroupIds", e.target.checked ? [...draft.securityGroupIds, sg.id] : draft.securityGroupIds.filter((item) => item !== sg.id))} /><span>{sg.name}<small>{sg.description}</small></span></label>)}</div></Field></ConfigSection>
      <ConfigSection title="存储配置" index="05"><div className="form-grid"><Field label={`系统盘 ${draft.systemDisk} GiB`}><div className="range-with-input"><input type="range" min="40" max="500" step="10" value={draft.systemDisk} onChange={(e) => set("systemDisk", Number(e.target.value))} /><label><input aria-label="系统盘容量" type="number" min="40" max="500" step="10" value={draft.systemDisk} onChange={(e) => set("systemDisk", Math.min(500, Math.max(40, Number(e.target.value))))} /><span>GiB</span></label></div></Field><Field label={`数据盘 ${draft.dataDisk} GiB`}><div className="range-with-input"><input type="range" min="0" max="2000" step="50" value={draft.dataDisk} onChange={(e) => set("dataDisk", Number(e.target.value))} /><label><input aria-label="数据盘容量" type="number" min="0" max="2000" step="50" value={draft.dataDisk} onChange={(e) => set("dataDisk", Math.min(2000, Math.max(0, Number(e.target.value))))} /><span>GiB</span></label></div></Field></div></ConfigSection>
      <ConfigSection title="购买信息" index="06"><div className="form-grid"><Field label="实例名称" required hint={errors.name}><input className={errors.name ? "invalid" : ""} placeholder="例如 app-prod-01" value={draft.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="资源组"><select value={draft.resourceGroupId} onChange={(e) => set("resourceGroupId", e.target.value)}>{state.resourceGroups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></Field><Field label="购买数量"><input type="number" min="1" max="10" value={draft.quantity} onChange={(e) => set("quantity", Math.min(10, Math.max(1, Number(e.target.value))))} /></Field><Field label={draft.billing === "monthly" ? "购买时长（月）" : "预计使用（小时）"}><input type="number" min="1" max={draft.billing === "monthly" ? 36 : 720} value={draft.duration} onChange={(e) => set("duration", Math.max(1, Number(e.target.value)))} /></Field></div>{draft.billing === "monthly" && <label className="switch-row"><input type="checkbox" checked={draft.autoRenew} onChange={(e) => set("autoRenew", e.target.checked)} /><span>到期自动续费</span></label>}</ConfigSection>
    </div><aside className="summary-card"><h2>配置摘要</h2><dl><dt>地区与可用区</dt><dd>{draft.region} / {draft.zone}</dd><dt>规格</dt><dd>{draft.cpu} vCPU / {draft.memory} GB / {draft.gpu}</dd><dt>镜像</dt><dd>{draft.image}</dd><dt>网络</dt><dd>{state.vpcs.find((v) => v.id === draft.vpcId)?.name} / {draft.publicIp ? `${draft.bandwidth} Mbps 公网` : "仅私网"}</dd><dt>存储</dt><dd>系统盘 {draft.systemDisk} GiB{draft.dataDisk ? ` + 数据盘 ${draft.dataDisk} GiB` : ""}</dd><dt>计费</dt><dd>{draft.billing === "monthly" ? `包月 ${draft.duration} 个月` : `按量 ${draft.duration} 小时`} · {draft.quantity} 台</dd></dl><div className="price"><span>配置费用</span><strong>{price.toFixed(2)} <small>USDT</small></strong><small>余额 {state.balance.toFixed(2)} USDT</small></div>{errors.balance && <p className="form-error">{errors.balance}</p>}<label className="agreement"><input type="checkbox" checked={draft.agreement} onChange={(e) => set("agreement", e.target.checked)} />我已阅读并同意《云服务协议》</label>{errors.agreement && <p className="form-error">{errors.agreement}</p>}<button className="button primary full" disabled={loading} onClick={review}>{loading ? "正在提交" : "确认订单"}</button></aside></div>
    {confirming && <Modal title="确认订单" description="提交后将立即扣除余额并创建资源。" onClose={() => setConfirming(false)} wide><div className="order-review"><div><span>实例名称</span><strong>{draft.name}</strong></div><div><span>实例规格</span><strong>{draft.cpu} vCPU / {draft.memory} GB / {draft.gpu}</strong></div><div><span>购买数量</span><strong>{draft.quantity} 台</strong></div><div><span>应付金额</span><strong>{price.toFixed(2)} USDT</strong></div></div><div className="modal-actions"><button className="button secondary" onClick={() => setConfirming(false)}>返回修改</button><button className="button primary" disabled={loading} onClick={submit}>{loading ? "正在创建资源" : "立即支付并创建"}</button></div></Modal>}</>;
}

function ConfigSection({ title, index, children }: { title: string; index: string; children: React.ReactNode }) { return <section className="config-section"><header><span>{index}</span><h2>{title}</h2></header><div>{children}</div></section>; }
