import { useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import {
  Copy, Download, Edit3, KeyRound, MoreHorizontal,
  Play, Plus, RotateCw, Search, Square, Trash2,
} from "lucide-react";
import { id, useConsoleStore } from "../../store";
import { api } from "../../api";
import type { Instance } from "../../domain";
import {
  Confirm, downloadCsv, EmptyState, PageHeader, Pagination, Panel, StatusBadge,
} from "../../shared";
import { EditInstanceModal, ResetPasswordModal } from "./InstanceDialogs";


export function InstancesPage() {
  const { state, mutate, createInstances, loading } = useConsoleStore(); const navigate = useNavigate(); const location = useLocation();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("全部状态"); const [region, setRegion] = useState(""); const [page, setPage] = useState(1); const [menuId, setMenuId] = useState(""); const [edit, setEdit] = useState<Instance | null>(null); const [reset, setReset] = useState<Instance | null>(null); const [remove, setRemove] = useState<Instance | null>(null);
  const regions = useMemo(() => [...new Set(state.instances.map((item) => item.region).filter(Boolean))], [state.instances]);
  const effectiveRegion = region || state.selectedRegion;
  const filtered = useMemo(() => state.instances.filter((item) => (!query || `${item.name}${item.id}${item.privateIp}${item.publicIp}`.toLowerCase().includes(query.toLowerCase())) && (status === "全部状态" || item.status === status) && (effectiveRegion === "全部地区" || !effectiveRegion || item.region === effectiveRegion)), [state.instances, query, status, effectiveRegion]);
  const stats = { running: filtered.filter((i) => i.status === "running").length, stopped: filtered.filter((i) => i.status === "stopped").length, cpu: filtered.reduce((n, i) => n + i.cpu, 0), memory: filtered.reduce((n, i) => n + i.memory, 0) };
  const action = async (instance: Instance, next: "running" | "stopped", text: string, providerAction: "start" | "stop" | "restart") => {
    if (instance.source === "aliyun-sync" && !instance.providerAccountId) { window.alert("该实例来自未绑定账号的阿里云同步快照，请先在系统管理中绑定云账号后再执行生命周期操作"); return; }
    try {
      await api.instanceAction(instance.id, providerAction);
      await mutate((s) => ({ ...s, instances: s.instances.map((i) => i.id === instance.id ? { ...i, status: next } : i), logs: [{ id: id("log"), instanceId: instance.id, action: text, operator: "admin", result: "成功", createdAt: new Date().toISOString() }, ...s.logs] }), `${instance.name} ${text}成功`);
    } catch (error) {
      window.alert(error instanceof Error ? `${text}失败：${error.message}` : `${text}失败`);
    }
  };
  const clone = async (instance: Instance) => { if (instance.source === "aliyun-sync") { window.alert("同步资源不能直接创建副本，请从创建云服务器流程重新选择规格"); return; } if (!instance.offeringId) { window.alert("该实例缺少后台规格标识，无法创建真实副本"); return; } await createInstances({ offeringId: instance.offeringId, name: `${instance.name}-copy`, region: instance.region, zone: instance.zone, billing: instance.billing, cpu: instance.cpu, memory: instance.memory, gpu: instance.gpu, image: instance.image, vpcId: instance.vpcId, subnetId: instance.subnetId, privateIp: "", publicIp: false, bandwidth: 0, loginType: "key", password: "", sshKey: "", systemDisk: instance.systemDisk, dataDisk: 0, securityGroupIds: instance.securityGroupIds, resourceGroupId: instance.resourceGroupId, quantity: 1, duration: 1, autoRenew: false, agreement: true }); };
  const exportCsv = () => downloadCsv("instances.csv", ["名称,实例ID,状态,规格,镜像,私有IP,公网IP,计费方式", ...filtered.map((i) => `${i.name},${i.id},${i.status},${i.cpu}C${i.memory}G,${i.image},${i.privateIp},${i.publicIp},${i.billing}`)]);
  const created = (location.state as { created?: string[] } | null)?.created ?? [];
  return <><PageHeader title="实例管理" description="查看和管理云服务器的生命周期、配置与网络信息。" actions={<><button className="button secondary" onClick={exportCsv}><Download size={16} />导出 CSV</button><button className="button primary" onClick={() => navigate("/instances/new")}><Plus size={16} />创建实例</button></>} />
    {created.length > 0 && <div className="inline-success">新实例已经创建并加入列表，可立即执行管理操作。</div>}
    <div className="mini-metrics"><div><span>实例总数</span><b>{filtered.length}</b></div><div><span>运行中</span><b className="green">{stats.running}</b></div><div><span>已停止</span><b>{stats.stopped}</b></div><div><span>总计算资源</span><b>{stats.cpu} 核 / {stats.memory} GiB</b></div></div>
    <Panel><div className="filters"><label className="search"><Search size={16} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="搜索名称、实例 ID 或 IP" /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option>全部状态</option><option value="running">运行中</option><option value="stopped">已停止</option></select><select value={effectiveRegion} onChange={(e) => setRegion(e.target.value)}><option>全部地区</option>{regions.map((item) => <option key={item}>{item}</option>)}</select><button className="button secondary" onClick={() => { setQuery(""); setStatus("全部状态"); setRegion(""); }}>重置</button></div>
      <div className="table-scroll"><table><thead><tr><th>实例名称 / ID</th><th>状态</th><th>规格</th><th>镜像</th><th>IP 地址</th><th>计费方式</th><th>操作</th></tr></thead><tbody>{filtered.slice((page - 1) * 8, page * 8).map((instance) => <tr key={instance.id} className={created.includes(instance.id) ? "highlight" : ""}><td><button className="link-stack" onClick={() => navigate(`/instances/${instance.id}`)}><strong>{instance.name}</strong><code>{instance.id}</code>{instance.source === "aliyun-sync" && <small>阿里云同步资源</small>}</button></td><td><StatusBadge value={instance.status} /></td><td>{instance.cpu} vCPU / {instance.memory} GiB<small>{instance.gpu}</small></td><td>{instance.image}</td><td><code>{instance.privateIp || "-"}</code><small>{instance.publicIp || "-"}</small></td><td>{instance.billing === "monthly" ? "包月" : "按量"}<small>{instance.price > 0 ? `${instance.price.toFixed(2)} USDT` : "云账号计费"}</small></td><td><div className="row-actions">{instance.status === "running" ? <button title="停止" disabled={loading} onClick={() => action(instance, "stopped", "停止", "stop")}><Square size={15} /></button> : <button title="启动" disabled={loading} onClick={() => action(instance, "running", "启动", "start")}><Play size={15} /></button>}<button title="重启" disabled={loading || instance.status !== "running"} onClick={() => action(instance, "running", "重启", "restart")}><RotateCw size={15} /></button><div className="more-wrap"><button title="更多操作" onClick={() => setMenuId(menuId === instance.id ? "" : instance.id)}><MoreHorizontal size={16} /></button>{menuId === instance.id && <div className="row-menu"><button onClick={() => { setEdit(instance); setMenuId(""); }}><Edit3 size={14} />编辑配置</button><button onClick={() => { setReset(instance); setMenuId(""); }}><KeyRound size={14} />重置密码</button><button onClick={() => { clone(instance); setMenuId(""); }}><Copy size={14} />创建副本</button><button className="danger-text" onClick={() => { setRemove(instance); setMenuId(""); }}><Trash2 size={14} />删除实例</button></div>}</div></div></td></tr>)}</tbody></table>{filtered.length === 0 && <EmptyState title={query ? "没有匹配的实例" : "暂无实例"} description="调整筛选条件，或创建一台新的云服务器。" />}</div><Pagination total={filtered.length} page={page} onChange={setPage} /></Panel>
    {edit && edit.source !== "aliyun-sync" && <EditInstanceModal instance={edit} onClose={() => setEdit(null)} />}{reset && reset.source !== "aliyun-sync" && <ResetPasswordModal instance={reset} onClose={() => setReset(null)} />}{remove && remove.source !== "aliyun-sync" && <Confirm title="删除实例" message={`确定删除“${remove.name}”吗？实例数据将无法恢复，关联公网 IP 和云盘将自动解绑。`} confirmText="确认删除" onClose={() => setRemove(null)} onConfirm={async () => { try { await api.deleteInstance(remove.id); const saved = await mutate((s) => ({ ...s, instances: s.instances.filter((i) => i.id !== remove.id), publicIps: s.publicIps.map((ip) => ip.instanceId === remove.id ? { ...ip, instanceId: undefined, status: "available" } : ip), disks: s.disks.map((disk) => disk.instanceId === remove.id ? { ...disk, instanceId: undefined, status: "available" } : disk), subnets: s.subnets.map((subnet) => subnet.id === remove.subnetId ? { ...subnet, availableIps: subnet.availableIps + 1 } : subnet), authorizations: s.authorizations.filter((authorization) => authorization.resourceId !== remove.id) }), "实例已删除并释放网络、存储关联"); if (saved) setRemove(null); } catch (error) { window.alert(error instanceof Error ? `删除失败：${error.message}` : "删除失败"); } }} />}</>;
}
