import { useState } from "react";
import { id, useConsoleStore } from "../../store";
import { api } from "../../api";
import type { Instance } from "../../domain";
import { Field, Modal } from "../../shared";

// Instances created through the purchase API use the backend public-id format
// (ins_<timestamp>_<random>) and can be updated remotely.
const isPersistedInstance = (instanceId: string) => instanceId.startsWith("ins_");

export function EditInstanceModal({ instance, onClose }: { instance: Instance; onClose: () => void }) { const { mutate, loading } = useConsoleStore(); const [name, setName] = useState(instance.name); const [cpu, setCpu] = useState(instance.cpu); const [memory, setMemory] = useState(instance.memory); const submit = async () => { if (!name.trim()) return; try { if (isPersistedInstance(instance.id)) await api.updateInstance(instance.id, { name }); const saved = await mutate((s) => ({ ...s, instances: s.instances.map((i) => i.id === instance.id ? { ...i, name, cpu, memory } : i) }), "实例配置已更新"); if (saved) onClose(); } catch (error) { window.alert(error instanceof Error ? `更新失败：${error.message}` : "更新失败"); } }; return <Modal title="编辑实例" description="修改名称和计算规格，保存后立即生效。" onClose={onClose}><div className="form-grid"><Field label="实例名称" required><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="vCPU"><select value={cpu} onChange={(e) => setCpu(Number(e.target.value))}>{[2, 4, 8, 16, 32].map((n) => <option key={n}>{n}</option>)}</select></Field><Field label="内存 (GiB)"><select value={memory} onChange={(e) => setMemory(Number(e.target.value))}>{[8, 16, 32, 64, 128].map((n) => <option key={n}>{n}</option>)}</select></Field></div><div className="modal-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={loading || !name.trim()} onClick={submit}>保存修改</button></div></Modal>; }
export function ResetPasswordModal({ instance, onClose }: { instance: Instance; onClose: () => void }) { const { mutate, loading } = useConsoleStore(); const [password, setPassword] = useState(""); const valid = /^(?=.*[A-Za-z])(?=.*\d).{8,}$/.test(password); return <Modal title="重置登录密码" description={`${instance.name} 将在密码更新后自动重启。`} onClose={onClose}><Field label="新密码" required hint={password && !valid ? "至少 8 位，并同时包含字母和数字" : ""}><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></Field><div className="modal-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={loading || !valid} onClick={async () => { try { await api.resetInstancePassword(instance.id, password); const saved = await mutate((s) => ({ ...s, logs: [{ id: id("log"), instanceId: instance.id, action: "重置密码", operator: "admin", result: "成功", createdAt: new Date().toISOString() }, ...s.logs] }), "密码已重置，实例正在重启"); if (saved) onClose(); } catch (error) { window.alert(error instanceof Error ? `重置失败：${error.message}` : "重置失败"); } }}>确认重置</button></div></Modal>; }
