import { useState } from "react";
import { Edit3, Search, Trash2, UserPlus } from "lucide-react";
import { id, useConsoleStore } from "../../store";
import type { ConsoleUser } from "../../domain";
import { Confirm, Field, formatDateTime as fmt, Modal, ModalSave, PageHeader, Panel, ResourceTable, StatusBadge } from "../../shared";

export function UsersPage() {
  const { state, mutate } = useConsoleStore(); const [query, setQuery] = useState(""); const [edit, setEdit] = useState<ConsoleUser | "new" | null>(null); const [remove, setRemove] = useState<ConsoleUser | null>(null); const users = state.users.filter((u) => !query || `${u.name}${u.email}${u.role}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader title="用户与权限" description="管理租户用户、角色和资源授权范围。" actions={<button className="button primary" onClick={() => setEdit("new")}><UserPlus size={16} />创建用户</button>} /><Panel><div className="filters"><label className="search"><Search size={16} /><input placeholder="搜索姓名、邮箱或角色" value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="button secondary" onClick={() => setQuery("")}>重置</button></div><ResourceTable heads={["用户", "角色", "授权范围", "状态", "创建时间", "操作"]}>{users.map((user) => <tr key={user.id}><td><div className="user-cell"><span>{user.name.slice(0, 1).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div></td><td>{user.role}</td><td>{user.scope}</td><td><StatusBadge value={user.status} /></td><td>{fmt(user.createdAt)}</td><td><div className="row-actions"><button title="编辑" onClick={() => setEdit(user)}><Edit3 size={15} /></button>{user.id !== "usr-root" && <button title="删除" onClick={() => setRemove(user)}><Trash2 size={15} /></button>}</div></td></tr>)}</ResourceTable></Panel>{edit && <UserModal value={edit} onClose={() => setEdit(null)} />}{remove && <Confirm title="删除用户" message={`确定删除用户“${remove.name}”吗？其资源授权将同时失效。`} onClose={() => setRemove(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, users: s.users.filter((u) => u.id !== remove.id), authorizations: s.authorizations.map((authorization) => ({ ...authorization, userIds: authorization.userIds.filter((userId) => userId !== remove.id) })) }), "用户已删除并清理资源授权"); if (saved) setRemove(null); }} />}</>;
}
function UserModal({ value, onClose }: { value: ConsoleUser | "new"; onClose: () => void }) { const { state, mutate } = useConsoleStore(); const [name, setName] = useState(value === "new" ? "" : value.name); const [email, setEmail] = useState(value === "new" ? "" : value.email); const [role, setRole] = useState<ConsoleUser["role"]>(value === "new" ? "只读用户" : value.role); const [scope, setScope] = useState(value === "new" ? "默认资源组" : value.scope); const validEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email); return <Modal title={value === "new" ? "创建用户" : "编辑用户权限"} onClose={onClose}><div className="form-grid"><Field label="用户名称"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="邮箱" hint={email && !validEmail ? "请输入有效邮箱地址" : ""}><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field><Field label="角色"><select value={role} onChange={(e) => setRole(e.target.value as ConsoleUser["role"])}><option>管理员</option><option>运维人员</option><option>只读用户</option></select></Field><Field label="授权范围"><select value={scope} onChange={(e) => setScope(e.target.value)}><option>全部资源</option>{state.resourceGroups.map((g) => <option key={g.id}>{g.name}</option>)}</select></Field></div><ModalSave disabled={!name.trim() || !validEmail} onClose={onClose} onSave={async () => { const saved = await mutate((s) => ({ ...s, users: value === "new" ? [{ id: id("usr"), name, email, role, scope, status: "active", createdAt: new Date().toISOString() }, ...s.users] : s.users.map((u) => u.id === value.id ? { ...u, name, email, role, scope } : u) }), value === "new" ? "用户已创建" : "用户权限已更新"); if (saved) onClose(); }} /></Modal>; }
