import { useState } from "react";
import { Copy, Edit3, Plus, Search, ShieldCheck, Trash2 } from "lucide-react";
import { id, useConsoleStore } from "../../store";
import type { ApiKey } from "../../domain";
import { Confirm, Field, formatDateTime as fmt, Modal, ModalSave, PageHeader, Panel, ResourceTable, StatusBadge } from "../../shared";

export function ApiKeysPage() {
  const { state, mutate } = useConsoleStore(); const [query, setQuery] = useState(""); const [edit, setEdit] = useState<ApiKey | "new" | null>(null); const [remove, setRemove] = useState<ApiKey | null>(null); const [secret, setSecret] = useState<{ access: string; secret: string } | null>(null); const keys = state.apiKeys.filter((key) => !query || `${key.name}${key.accessKey}`.toLowerCase().includes(query.toLowerCase()));
  const copy = async (text: string) => { await navigator.clipboard.writeText(text); await mutate((s) => s, "Access Key 已复制"); };
  return <><PageHeader title="API 密钥" description="创建和管理用于自动化、CLI 与第三方集成的访问凭证。" actions={<button className="button primary" onClick={() => setEdit("new")}><Plus size={16} />创建 API Key</button>} /><div className="security-note"><ShieldCheck size={19} /><p><strong>妥善保管访问密钥</strong>Secret 只会在创建成功时完整显示一次。建议定期轮换并遵循最小权限原则。</p></div><Panel><div className="filters"><label className="search"><Search size={16} /><input placeholder="搜索密钥名称或 Access Key" value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="button secondary" onClick={() => setQuery("")}>重置</button></div><ResourceTable heads={["密钥名称", "Access Key", "Secret", "状态", "最近使用", "创建时间", "操作"]}>{keys.map((key) => <tr key={key.id}><td><strong>{key.name}</strong><small>{key.id}</small></td><td><button className="copy-value" title="复制 Access Key" onClick={() => copy(key.accessKey)}><code>{key.accessKey}</code><Copy size={14} /></button></td><td><code>{key.secretHint}</code></td><td><StatusBadge value={key.status} /></td><td>{key.lastUsedAt ? fmt(key.lastUsedAt) : "从未使用"}</td><td>{fmt(key.createdAt)}</td><td><div className="row-actions"><button title="编辑" onClick={() => setEdit(key)}><Edit3 size={15} /></button>{key.status !== "revoked" && <button className="text-button" onClick={() => mutate((s) => ({ ...s, apiKeys: s.apiKeys.map((k) => k.id === key.id ? { ...k, status: key.status === "paused" ? "active" : "paused" } : k) }), key.status === "paused" ? "密钥已启用" : "密钥已暂停")}>{key.status === "paused" ? "启用" : "暂停"}</button>}<button title="撤销" disabled={key.status === "revoked"} onClick={() => setRemove(key)}><Trash2 size={15} /></button></div></td></tr>)}</ResourceTable></Panel>
    {edit && <ApiKeyModal value={edit} onClose={() => setEdit(null)} onCreated={(access, value) => setSecret({ access, secret: value })} />}{secret && <Modal title="API Key 创建成功" description="请立即保存 Secret，关闭后将无法再次查看。" onClose={() => setSecret(null)}><div className="secret-box"><label>Access Key<button onClick={() => navigator.clipboard.writeText(secret.access)}><Copy size={14} />复制</button></label><code>{secret.access}</code><label>Secret<button onClick={() => navigator.clipboard.writeText(secret.secret)}><Copy size={14} />复制</button></label><code>{secret.secret}</code></div><div className="modal-actions"><button className="button primary" onClick={() => setSecret(null)}>我已保存</button></div></Modal>}{remove && <Confirm title="撤销 API Key" message={`撤销“${remove.name}”后，使用该密钥的程序将立即无法访问。`} confirmText="确认撤销" onClose={() => setRemove(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, apiKeys: s.apiKeys.map((k) => k.id === remove.id ? { ...k, status: "revoked" } : k) }), "API Key 已撤销"); if (saved) setRemove(null); }} />}</>;
}
function ApiKeyModal({ value, onClose, onCreated }: { value: ApiKey | "new"; onClose: () => void; onCreated: (access: string, secret: string) => void }) { const { mutate } = useConsoleStore(); const [name, setName] = useState(value === "new" ? "" : value.name); return <Modal title={value === "new" ? "创建 API Key" : "编辑 API Key"} onClose={onClose}><Field label="密钥名称" required><input value={name} onChange={(e) => setName(e.target.value)} placeholder="例如 CI/CD 自动化" /></Field><ModalSave disabled={!name} onClose={onClose} onSave={async () => { if (value === "new") { const access = `HB${crypto.randomUUID().replaceAll("-", "").slice(0, 12).toUpperCase()}`; const secret = `hbs_${crypto.randomUUID().replaceAll("-", "")}`; const saved = await mutate((s) => ({ ...s, apiKeys: [{ id: id("key"), name, accessKey: access, secretHint: `****${secret.slice(-4)}`, status: "active", createdAt: new Date().toISOString() }, ...s.apiKeys] }), "API Key 已创建"); if (!saved) return; onClose(); onCreated(access, secret); } else { const saved = await mutate((s) => ({ ...s, apiKeys: s.apiKeys.map((k) => k.id === value.id ? { ...k, name } : k) }), "API Key 已更新"); if (saved) onClose(); } }} /></Modal>; }
