import { useState } from "react";
import { Edit3, Plus, Search, Trash2 } from "lucide-react";
import { id, useConsoleStore } from "../../store";
import type { QuotaRequest, ResourceGroup, Tag } from "../../domain";
import { Confirm, EmptyState, Field, formatDateTime as fmt, Modal, PageHeader, Panel, ResourceTable, SimpleRequestModal, StatusBadge, Tabs } from "../../shared";

export function ResourcesPage() {
  const { state, mutate } = useConsoleStore(); const [tab, setTab] = useState("资源"); const [query, setQuery] = useState(""); const [type, setType] = useState("全部类型"); const [group, setGroup] = useState("全部资源组"); const [groupEdit, setGroupEdit] = useState<ResourceGroup | "new" | null>(null); const [tagEdit, setTagEdit] = useState<Tag | "new" | null>(null); const [quota, setQuota] = useState(false); const [authResourceId, setAuthResourceId] = useState<string | null>(null); const [removeGroup, setRemoveGroup] = useState<ResourceGroup | null>(null); const [removeTag, setRemoveTag] = useState<Tag | null>(null); const [removeQuota, setRemoveQuota] = useState<QuotaRequest | null>(null);
  const allResources = [...state.instances.map((item) => ({ id: item.id, name: item.name, type: "云服务器", groupId: item.resourceGroupId, region: item.region, status: item.status })), ...state.disks.map((item) => ({ id: item.id, name: item.name, type: "云盘", groupId: "", region: item.region, status: item.status })), ...state.publicIps.map((item) => ({ id: item.id, name: item.address, type: "公网 IP", groupId: "", region: item.region, status: item.status }))];
  const regionResources = allResources.filter((item) => !state.selectedRegion || item.region === state.selectedRegion);
  const resources = regionResources.filter((item) => (!query || `${item.name}${item.id}`.toLowerCase().includes(query.toLowerCase())) && (type === "全部类型" || item.type === type) && (group === "全部资源组" || item.groupId === group));
  return <><PageHeader title="资源中心" description="按资源组、标签和订阅统一组织与授权云资源。" actions={<button className="button primary" onClick={() => setGroupEdit("new")}><Plus size={16} />创建资源组</button>} /><Panel><Tabs items={["资源", "资源组", "订阅", "标签", "配额"]} value={tab} onChange={setTab} />
    {tab === "资源" && <><div className="filters"><label className="search"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索资源名称或 ID" /></label><select value={type} onChange={(e) => setType(e.target.value)}><option>全部类型</option><option>云服务器</option><option>云盘</option><option>公网 IP</option></select><select value={group} onChange={(e) => setGroup(e.target.value)}><option>全部资源组</option>{state.resourceGroups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="button secondary" onClick={() => { setQuery(""); setType("全部类型"); setGroup("全部资源组"); }}>重置</button></div><div className="table-scroll"><table><thead><tr><th>资源名称 / ID</th><th>类型</th><th>资源组</th><th>区域</th><th>状态</th><th>操作</th></tr></thead><tbody>{resources.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.type}</td><td>{state.resourceGroups.find((g) => g.id === item.groupId)?.name}</td><td>{item.region}</td><td><StatusBadge value={item.status} /></td><td><button className="text-button" onClick={() => setAuthResourceId(item.id)}>授权设置</button></td></tr>)}</tbody></table>{resources.length === 0 && <EmptyState title="没有匹配资源" />}</div></>}
    {tab === "资源组" && <div className="table-scroll"><table><thead><tr><th>资源组</th><th>描述</th><th>所有者</th><th>资源数量</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{state.resourceGroups.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.description}</td><td>{item.owner}</td><td>{regionResources.filter((resource) => resource.groupId === item.id).length}</td><td>{fmt(item.createdAt)}</td><td><div className="row-actions"><button title="编辑" onClick={() => setGroupEdit(item)}><Edit3 size={15} /></button>{item.id !== "rg-default" && <button title="删除" onClick={() => setRemoveGroup(item)}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div>}
    {tab === "订阅" && <EmptyState title="暂无订阅数据" description="订阅信息将在云平台同步接口提供后显示。" />}
    {tab === "标签" && <><div className="tab-actions"><span>通过标签对跨资源组资源进行分类。</span><button className="button primary" onClick={() => setTagEdit("new")}><Plus size={15} />创建标签</button></div><div className="table-scroll"><table><thead><tr><th>标签键</th><th>标签值</th><th>关联资源</th><th>操作</th></tr></thead><tbody>{state.tags.map((item) => <tr key={item.id}><td><code>{item.key}</code></td><td>{item.value}</td><td>{item.resourceCount}</td><td><div className="row-actions"><button title="编辑" onClick={() => setTagEdit(item)}><Edit3 size={15} /></button><button title="删除" onClick={() => setRemoveTag(item)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div></>}
    {tab === "配额" && <><div className="tab-actions"><span>配额上限需从云平台接口同步。</span><button className="button primary" onClick={() => setQuota(true)}>申请调整配额</button></div><EmptyState title="暂无配额数据" description="当前账号未同步到云平台配额信息。" /><h3 className="form-subtitle">申请记录</h3><ResourceTable heads={["申请编号", "配额类型", "目标配额", "原因", "状态", "申请时间", "操作"]}>{state.quotaRequests.map((request) => <tr key={request.id}><td><code>{request.id}</code></td><td>{request.resource}</td><td>{request.requested}</td><td>{request.reason}</td><td><StatusBadge value={request.status} /></td><td>{fmt(request.createdAt)}</td><td><button className="icon-button" title="删除申请" onClick={() => setRemoveQuota(request)}><Trash2 size={15} /></button></td></tr>)}</ResourceTable>{state.quotaRequests.length === 0 && <EmptyState title="暂无配额申请" />}</>}</Panel>
    {groupEdit && <ResourceGroupModal value={groupEdit} onClose={() => setGroupEdit(null)} />}{tagEdit && <TagModal value={tagEdit} onClose={() => setTagEdit(null)} />}{quota && <SimpleRequestModal title="申请调整配额" fields={["配额类型", "目标配额", "申请原因"]} onClose={() => setQuota(false)} onSubmit={async ([resource, requested, reason]) => { const saved = await mutate((s) => ({ ...s, quotaRequests: [{ id: id("quota"), resource, requested: Math.max(1, Number(requested) || 1), reason, status: "pending", createdAt: new Date().toISOString() }, ...s.quotaRequests] }), `已提交${resource}配额申请`); if (saved) setQuota(false); }} />}{authResourceId && <AuthorizationModal resourceId={authResourceId} onClose={() => setAuthResourceId(null)} />}{removeGroup && <Confirm title="删除资源组" message={`确定删除“${removeGroup.name}”吗？其中的实例将迁移到默认资源组。`} onClose={() => setRemoveGroup(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, resourceGroups: s.resourceGroups.filter((g) => g.id !== removeGroup.id), instances: s.instances.map((instance) => instance.resourceGroupId === removeGroup.id ? { ...instance, resourceGroupId: "rg-default" } : instance) }), "资源组已删除并迁移关联资源"); if (saved) setRemoveGroup(null); }} />}{removeTag && <Confirm title="删除标签" message={`确定删除标签“${removeTag.key}: ${removeTag.value}”吗？`} onClose={() => setRemoveTag(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, tags: s.tags.filter((tag) => tag.id !== removeTag.id) }), "标签已删除"); if (saved) setRemoveTag(null); }} />}{removeQuota && <Confirm title="删除配额申请" message={`确定删除申请“${removeQuota.id}”吗？`} onClose={() => setRemoveQuota(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, quotaRequests: s.quotaRequests.filter((request) => request.id !== removeQuota.id) }), "配额申请已删除"); if (saved) setRemoveQuota(null); }} />}</>;
}

function ResourceGroupModal({ value, onClose }: { value: ResourceGroup | "new"; onClose: () => void }) { const { mutate, loading } = useConsoleStore(); const [name, setName] = useState(value === "new" ? "" : value.name); const [description, setDescription] = useState(value === "new" ? "" : value.description); return <Modal title={value === "new" ? "创建资源组" : "编辑资源组"} onClose={onClose}><div className="form-grid single"><Field label="资源组名称" required><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="描述"><textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field></div><div className="modal-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={loading || !name.trim()} onClick={async () => { const saved = await mutate((s) => ({ ...s, resourceGroups: value === "new" ? [{ id: id("rg"), name, description, owner: "admin", createdAt: new Date().toISOString() }, ...s.resourceGroups] : s.resourceGroups.map((g) => g.id === value.id ? { ...g, name, description } : g) }), value === "new" ? "资源组已创建" : "资源组已更新"); if (saved) onClose(); }}>保存</button></div></Modal>; }
function TagModal({ value, onClose }: { value: Tag | "new"; onClose: () => void }) { const { mutate } = useConsoleStore(); const [key, setKey] = useState(value === "new" ? "" : value.key); const [tagValue, setTagValue] = useState(value === "new" ? "" : value.value); return <Modal title={value === "new" ? "创建标签" : "编辑标签"} onClose={onClose}><div className="form-grid"><Field label="标签键" required><input value={key} onChange={(e) => setKey(e.target.value)} /></Field><Field label="标签值" required><input value={tagValue} onChange={(e) => setTagValue(e.target.value)} /></Field></div><div className="modal-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={!key || !tagValue} onClick={async () => { const saved = await mutate((s) => ({ ...s, tags: value === "new" ? [{ id: id("tag"), key, value: tagValue, resourceCount: 0 }, ...s.tags] : s.tags.map((t) => t.id === value.id ? { ...t, key, value: tagValue } : t) }), value === "new" ? "标签已创建" : "标签已更新"); if (saved) onClose(); }}>保存</button></div></Modal>; }
function AuthorizationModal({ resourceId, onClose }: { resourceId: string; onClose: () => void }) { const { state, mutate, loading } = useConsoleStore(); const current = state.authorizations.find((item) => item.resourceId === resourceId); const [users, setUsers] = useState(current?.userIds ?? []); return <Modal title="资源授权设置" description={`资源标识：${resourceId}`} onClose={onClose}><div className="check-list">{state.users.map((user) => <label key={user.id}><input type="checkbox" checked={users.includes(user.id)} onChange={(e) => setUsers(e.target.checked ? [...users, user.id] : users.filter((userId) => userId !== user.id))} /><span>{user.name}<small>{user.role} · {user.email}</small></span></label>)}</div><div className="modal-actions"><button className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={loading} onClick={async () => { const saved = await mutate((s) => ({ ...s, authorizations: s.authorizations.some((item) => item.resourceId === resourceId) ? s.authorizations.map((item) => item.resourceId === resourceId ? { ...item, userIds: users, updatedAt: new Date().toISOString() } : item) : [{ id: id("auth"), resourceId, userIds: users, updatedAt: new Date().toISOString() }, ...s.authorizations] }), `已保存资源授权 ${resourceId}`); if (saved) onClose(); }}>保存授权</button></div></Modal>; }
