import { useEffect, useMemo, useState } from "react";
import { Edit3, Plus, RefreshCw, Search, ShieldOff } from "lucide-react";
import { api, type AdminAliyunRegion, type AdminAliyunZone } from "../../api";
import { Confirm, EmptyState, Field, Modal, ModalSave, PageHeader, Panel, ResourceTable, StatusBadge, Tabs } from "../../shared";

type RegionForm = { code: string; name: string; status: "active" | "disabled" };
type ZoneForm = { region_id: string; zone_code: string; name: string; status: "active" | "disabled" };

export function AdminAliyunCatalogPage() {
  const [tab, setTab] = useState("可用区"); const [regions, setRegions] = useState<AdminAliyunRegion[]>([]); const [zones, setZones] = useState<AdminAliyunZone[]>([]); const [query, setQuery] = useState("");
  const [regionEdit, setRegionEdit] = useState<AdminAliyunRegion | "new" | null>(null); const [zoneEdit, setZoneEdit] = useState<AdminAliyunZone | "new" | null>(null); const [remove, setRemove] = useState<{ type: "region" | "zone"; id: string; name: string } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [nextRegions, nextZones] = await Promise.all([api.adminAliyunRegions(), api.adminAliyunZones()]); setRegions(nextRegions); setZones(nextZones); } catch (err) { setError(err instanceof Error ? err.message : "云基础数据加载失败"); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const filteredRegions = useMemo(() => regions.filter((item) => `${item.code}${item.name}${item.status}`.toLowerCase().includes(query.toLowerCase())), [regions, query]);
  const filteredZones = useMemo(() => zones.filter((item) => `${item.zone_code}${item.name}${item.region_code}${item.region_name}${item.status}`.toLowerCase().includes(query.toLowerCase())), [zones, query]);
  return <><PageHeader eyebrow="SYSTEM ADMINISTRATION" title="云基础数据" description="维护阿里云地域和可用区目录，供资源创建、筛选和账号配置使用。" actions={<><button className="button secondary" disabled={loading} onClick={() => void load()}><RefreshCw size={15} />刷新</button>{tab === "地域" ? <button className="button primary" onClick={() => setRegionEdit("new")}><Plus size={16} />新增地域</button> : <button className="button primary" onClick={() => setZoneEdit("new")}><Plus size={16} />新增可用区</button>}</>} />
    {error && <div className="security-note"><ShieldOff size={18} /><p>{error}</p></div>}
    <Panel><Tabs items={["可用区", "地域"]} value={tab} onChange={(value) => { setTab(value); setQuery(""); }} /><div className="filters"><label className="search"><Search size={16} /><input placeholder={tab === "地域" ? "搜索地域 ID 或名称" : "搜索可用区、地域或名称"} value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="button secondary" onClick={() => setQuery("")}>重置</button></div>{tab === "地域" ? <ResourceTable heads={["地域", "状态", "可用区数量", "更新时间", "操作"]}>{filteredRegions.map((region) => <tr key={region.id}><td><strong>{region.name}</strong><small>{region.code}</small></td><td><StatusBadge value={region.status} /></td><td>{region.zone_count}</td><td>{new Date(region.updated_at).toLocaleString("zh-CN")}</td><td><div className="row-actions"><button title="编辑" onClick={() => setRegionEdit(region)}><Edit3 size={15} /></button><button title="停用" disabled={region.status === "disabled"} onClick={() => setRemove({ type: "region", id: region.id, name: region.name })}><ShieldOff size={15} /></button></div></td></tr>)}</ResourceTable> : <ResourceTable heads={["可用区", "所属地域", "状态", "更新时间", "操作"]}>{filteredZones.map((zone) => <tr key={zone.id}><td><strong>{zone.name}</strong><small>{zone.zone_code}</small></td><td>{zone.region_name}<small>{zone.region_code}</small></td><td><StatusBadge value={zone.status} /></td><td>{new Date(zone.updated_at).toLocaleString("zh-CN")}</td><td><div className="row-actions"><button title="编辑" onClick={() => setZoneEdit(zone)}><Edit3 size={15} /></button><button title="停用" disabled={zone.status === "disabled"} onClick={() => setRemove({ type: "zone", id: zone.id, name: zone.name })}><ShieldOff size={15} /></button></div></td></tr>)}</ResourceTable>}{(tab === "地域" ? filteredRegions.length : filteredZones.length) === 0 && <EmptyState title={query ? "没有匹配结果" : "暂无基础数据"} description="可以新增一条目录数据，或等待云账号同步。" />}</Panel>
    {regionEdit && <RegionModal value={regionEdit} onClose={() => setRegionEdit(null)} onSaved={async () => { setRegionEdit(null); await load(); }} />}{zoneEdit && <ZoneModal value={zoneEdit} regions={regions} onClose={() => setZoneEdit(null)} onSaved={async () => { setZoneEdit(null); await load(); }} />}{remove && <Confirm title={`停用${remove.type === "region" ? "地域" : "可用区"}`} message={`停用“${remove.name}”后，新资源创建时不会再推荐该目录数据。`} confirmText="确认停用" onClose={() => setRemove(null)} onConfirm={async () => { if (remove.type === "region") await api.disableAdminAliyunRegion(remove.id); else await api.disableAdminAliyunZone(remove.id); setRemove(null); await load(); }} />}
  </>;
}

function RegionModal({ value, onClose, onSaved }: { value: AdminAliyunRegion | "new"; onClose: () => void; onSaved: () => Promise<void> }) { const [form, setForm] = useState<RegionForm>(() => value === "new" ? { code: "", name: "", status: "active" } : { code: value.code, name: value.name, status: value.status === "disabled" ? "disabled" : "active" }); const [error, setError] = useState(""); return <Modal title={value === "new" ? "新增地域" : "编辑地域"} description="地域 ID 使用阿里云标准编码，例如 cn-hangzhou。" onClose={onClose}><div className="form-grid"><Field label="地域 ID" required><input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></Field><Field label="地域名称" required><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="状态"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as RegionForm["status"] })}><option value="active">启用</option><option value="disabled">停用</option></select></Field></div>{error && <p className="form-error">{error}</p>}<ModalSave disabled={!form.code.trim() || !form.name.trim()} onClose={onClose} onSave={async () => { try { setError(""); if (value === "new") await api.createAdminAliyunRegion(form); else await api.updateAdminAliyunRegion(value.id, form); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "保存失败"); } }} /></Modal>; }

function ZoneModal({ value, regions, onClose, onSaved }: { value: AdminAliyunZone | "new"; regions: AdminAliyunRegion[]; onClose: () => void; onSaved: () => Promise<void> }) { const [form, setForm] = useState<ZoneForm>(() => value === "new" ? { region_id: regions[0]?.id ?? "", zone_code: "", name: "", status: "active" } : { region_id: value.region_id, zone_code: value.zone_code, name: value.name, status: value.status === "disabled" ? "disabled" : "active" }); const [error, setError] = useState(""); return <Modal title={value === "new" ? "新增可用区" : "编辑可用区"} description="可用区 ID 使用阿里云标准编码，例如 cn-hangzhou-h。" onClose={onClose}><div className="form-grid"><Field label="所属地域" required><select value={form.region_id} onChange={(e) => setForm({ ...form, region_id: e.target.value })}>{regions.filter((region) => region.status === "active").map((region) => <option key={region.id} value={region.id}>{region.name}（{region.code}）</option>)}</select></Field><Field label="可用区 ID" required><input value={form.zone_code} onChange={(e) => setForm({ ...form, zone_code: e.target.value })} /></Field><Field label="可用区名称" required><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="状态"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ZoneForm["status"] })}><option value="active">启用</option><option value="disabled">停用</option></select></Field></div>{error && <p className="form-error">{error}</p>}<ModalSave disabled={!form.region_id || !form.zone_code.trim() || !form.name.trim()} onClose={onClose} onSave={async () => { try { setError(""); if (value === "new") await api.createAdminAliyunZone(form); else await api.updateAdminAliyunZone(value.id, form); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "保存失败"); } }} /></Modal>; }
