import { useState } from "react";
import { Download, WalletCards } from "lucide-react";
import { useConsoleStore } from "../../store";
import { downloadCsv as csv, formatDateTime as fmt, Metric, PageHeader, Panel, ResourceTable, StatusBadge, Tabs } from "../../shared";

export function BillingPage({ onRecharge }: { onRecharge: () => void }) {
  const { state } = useConsoleStore(); const [tab, setTab] = useState("费用概览"); const [product, setProduct] = useState("全部产品"); const [period, setPeriod] = useState("本月");
  const now = new Date(); const periodStart = period === "本月" ? new Date(now.getFullYear(), now.getMonth(), 1) : period === "上月" ? new Date(now.getFullYear(), now.getMonth() - 1, 1) : new Date(now.getTime() - 90 * 86400000); const periodEnd = period === "上月" ? new Date(now.getFullYear(), now.getMonth(), 1) : now;
  const records = state.billing.filter((item) => (product === "全部产品" || item.product === product) && new Date(item.createdAt) >= periodStart && new Date(item.createdAt) <= periodEnd); const consumption = Math.abs(records.filter((r) => r.type === "consume").reduce((a, b) => a + b.amount, 0));
  return <><PageHeader title="用量与账单" description="查看账户余额、订单、消费趋势和充值记录。" actions={<><button className="button secondary" onClick={() => csv("hexbit-billing.csv", ["记录ID,类型,产品,金额,时间", ...records.map((r) => `${r.id},${r.type},${r.product},${r.amount},${r.createdAt}`)])}><Download size={16} />导出账单</button><button className="button primary" onClick={onRecharge}><WalletCards size={16} />账户充值</button></>} /><div className="metrics-grid three"><Metric label="账户余额" value={`${state.balance.toFixed(2)} USDT`} detail="可用于支付云资源" /><Metric label="本月消费" value={`${consumption.toFixed(2)} USDT`} detail="较上月下降 8.3%" tone="orange" /><Metric label="待支付订单" value={state.orders.filter((o) => o.status === "pending").length} detail="请及时完成支付" tone="green" /></div><Panel><Tabs items={["费用概览", "订单", "账单明细", "充值记录", "成本分析"]} value={tab} onChange={setTab} /><div className="filters billing-filter"><select value={product} onChange={(e) => setProduct(e.target.value)}><option>全部产品</option><option>云服务器</option><option>云盘</option><option>账户充值</option></select><select value={period} onChange={(e) => setPeriod(e.target.value)}><option>本月</option><option>上月</option><option>近 90 天</option></select><button className="button secondary" onClick={() => { setProduct("全部产品"); setPeriod("本月"); }}>重置</button></div>
    {tab === "费用概览" && <div className="billing-overview"><article><h3>每日消费趋势</h3><div className="bar-chart tall blue">{Array.from({ length: 20 }, (_, i) => <i key={i} style={{ height: `${18 + i * 11 % 70}%` }} />)}</div><div className="chart-axis"><span>08-01</span><span>08-08</span><span>08-15</span><span>今天</span></div></article><article><h3>产品费用占比</h3><div className="donut" style={{ background: "conic-gradient(#1677d2 0 72%, #2aa876 72% 88%, #f2a23a 88% 100%)" }}><span><b>100%</b>总消费</span></div><div className="legend"><span><i className="blue-bg" />云服务器 72%</span><span><i className="green-bg" />云盘 16%</span><span><i className="orange-bg" />网络 12%</span></div></article></div>}
    {tab === "订单" && <ResourceTable heads={["订单号", "资源名称", "订单类型", "状态", "创建时间", "支付时间", "金额"]}>{state.orders.map((order) => <tr key={order.id}><td><code>{order.id}</code></td><td>{order.resourceName}</td><td>{order.type === "purchase" ? "新购" : "续费"}</td><td><StatusBadge value={order.status} /></td><td>{fmt(order.createdAt)}</td><td>{order.paidAt ? fmt(order.paidAt) : "-"}</td><td><strong>{order.amount.toFixed(2)} USDT</strong></td></tr>)}</ResourceTable>}
    {tab === "账单明细" && <BillingRecords records={records.filter((r) => r.type === "consume")} />}{tab === "充值记录" && <BillingRecords records={records.filter((r) => r.type === "recharge")} />}
    {tab === "成本分析" && <div className="cost-grid">{state.resourceGroups.map((group, index) => <article key={group.id}><span>{group.name}</span><strong>{(consumption * [.68, .24, .08][index % 3]).toFixed(2)} USDT</strong><div><i style={{ width: `${[68, 24, 8][index % 3]}%` }} /></div><small>占本期费用 {[68, 24, 8][index % 3]}%</small></article>)}</div>}</Panel></>;
}
function BillingRecords({ records }: { records: ReturnType<typeof useConsoleStore>["state"]["billing"] }) { return <ResourceTable heads={["记录 ID", "类型", "产品", "关联订单", "金额", "时间"]}>{records.map((record) => <tr key={record.id}><td><code>{record.id}</code></td><td>{record.type === "consume" ? "消费" : "充值"}</td><td>{record.product}</td><td>{record.orderId ?? "-"}</td><td className={record.amount > 0 ? "amount-positive" : ""}>{record.amount > 0 ? "+" : ""}{record.amount.toFixed(2)} USDT</td><td>{fmt(record.createdAt)}</td></tr>)}</ResourceTable>; }
