import { useState } from "react";
import { Activity, Edit3, Plus, Trash2 } from "lucide-react";
import { id, useConsoleStore } from "../../store";
import type { AlertRule } from "../../domain";
import { Confirm, Field, formatDateTime as fmt, Modal, ModalSave, PageHeader, Panel, ResourceTable, StatusBadge, Tabs } from "../../shared";

export function MonitoringPage() {
  const { state, mutate } = useConsoleStore(); const [tab, setTab] = useState("监控概览"); const [edit, setEdit] = useState<AlertRule | "new" | null>(null); const [removeRule, setRemoveRule] = useState<AlertRule | null>(null);
  const healthy = state.instances.filter((i) => i.status !== "error").length;
  return <><PageHeader title="云监控" description="观察资源健康度、性能趋势、告警和操作事件。" actions={<button className="button primary" onClick={() => setEdit("new")}><Plus size={16} />创建告警规则</button>} /><Panel><Tabs items={["监控概览", "告警规则", "告警历史", "事件与日志"]} value={tab} onChange={setTab} />
    {tab === "监控概览" && <><div className="health-strip"><div><Activity size={24} /><strong>{healthy}/{state.instances.length}</strong><span>资源健康</span></div><p>当前计算、网络和存储服务运行正常。最近 24 小时无严重告警。</p></div><div className="chart-grid monitor-main">{[{ n: "CPU 平均使用率", v: 42, c: "blue" }, { n: "内存平均使用率", v: 58, c: "green" }, { n: "磁盘平均使用率", v: 47, c: "orange" }, { n: "网络吞吐", v: 72, c: "red" }].map((item, ci) => <Panel key={item.n} title={item.n}><div className="chart-summary"><strong>{item.v}<small>{item.n === "网络吞吐" ? " Mbps" : "%"}</small></strong><span>最近 24 小时</span></div><div className={`bar-chart ${item.c}`}>{Array.from({ length: 24 }, (_, i) => <i key={i} style={{ height: `${20 + (i * 13 + ci * 19) % 70}%` }} />)}</div></Panel>)}</div></>}
    {tab === "告警规则" && <ResourceTable heads={["规则名称", "资源", "指标", "触发条件", "严重级别", "状态", "操作"]}>{state.alertRules.map((rule) => <tr key={rule.id}><td><strong>{rule.name}</strong><small>{rule.id}</small></td><td>{rule.resource}</td><td>{rule.metric}</td><td>&gt; {rule.threshold}% 持续 {rule.duration} 分钟</td><td>{rule.severity}</td><td><label className="switch-row compact"><input type="checkbox" checked={rule.enabled} onChange={(e) => mutate((s) => ({ ...s, alertRules: s.alertRules.map((r) => r.id === rule.id ? { ...r, enabled: e.target.checked } : r) }), e.target.checked ? "告警规则已启用" : "告警规则已停用")} /><span>{rule.enabled ? "启用" : "停用"}</span></label></td><td><div className="row-actions"><button title="编辑" onClick={() => setEdit(rule)}><Edit3 size={15} /></button><button title="删除" onClick={() => setRemoveRule(rule)}><Trash2 size={15} /></button></div></td></tr>)}</ResourceTable>}
    {tab === "告警历史" && <ResourceTable heads={["告警规则", "资源", "级别", "状态", "发生时间"]}>{state.alertEvents.map((event) => <tr key={event.id}><td>{event.ruleName}</td><td>{event.resource}</td><td>{event.severity}</td><td><StatusBadge value={event.status} /></td><td>{fmt(event.occurredAt)}</td></tr>)}</ResourceTable>}
    {tab === "事件与日志" && <div className="timeline global">{state.logs.map((log) => <article key={log.id}><i /><div><strong>{log.action}</strong><span>{state.instances.find((ins) => ins.id === log.instanceId)?.name ?? log.instanceId} · {log.operator} · {fmt(log.createdAt)}</span></div><StatusBadge value={log.result} /></article>)}</div>}</Panel>{edit && <AlertModal value={edit} onClose={() => setEdit(null)} />}{removeRule && <Confirm title="删除告警规则" message={`确定删除“${removeRule.name}”吗？`} onClose={() => setRemoveRule(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, alertRules: s.alertRules.filter((rule) => rule.id !== removeRule.id) }), "告警规则已删除"); if (saved) setRemoveRule(null); }} />}</>;
}
function AlertModal({ value, onClose }: { value: AlertRule | "new"; onClose: () => void }) { const { state, mutate } = useConsoleStore(); const [name, setName] = useState(value === "new" ? "" : value.name); const [metric, setMetric] = useState<AlertRule["metric"]>(value === "new" ? "CPU" : value.metric); const [threshold, setThreshold] = useState(value === "new" ? 80 : value.threshold); const [duration, setDuration] = useState(value === "new" ? 5 : value.duration); const [resource, setResource] = useState(value === "new" ? "全部实例" : value.resource); return <Modal title={value === "new" ? "创建告警规则" : "编辑告警规则"} onClose={onClose}><div className="form-grid"><Field label="规则名称"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="监控资源"><select value={resource} onChange={(e) => setResource(e.target.value)}><option>全部实例</option>{state.instances.map((i) => <option key={i.id}>{i.name}</option>)}</select></Field><Field label="指标"><select value={metric} onChange={(e) => setMetric(e.target.value as AlertRule["metric"])}><option>CPU</option><option>内存</option><option>磁盘</option><option>网络</option></select></Field><Field label="阈值 (%)"><input type="number" min="1" max="100" value={threshold} onChange={(e) => setThreshold(Number(e.target.value))} /></Field><Field label="持续时间（分钟）"><input type="number" min="1" value={duration} onChange={(e) => setDuration(Number(e.target.value))} /></Field></div><ModalSave disabled={!name || threshold < 1 || threshold > 100 || duration < 1} onClose={onClose} onSave={async () => { const saved = await mutate((s) => ({ ...s, alertRules: value === "new" ? [{ id: id("alert"), name, metric, threshold, duration, enabled: true, severity: "警告", resource }, ...s.alertRules] : s.alertRules.map((r) => r.id === value.id ? { ...r, name, metric, threshold, duration, resource } : r) }), value === "new" ? "告警规则已创建" : "告警规则已更新"); if (saved) onClose(); }} /></Modal>; }
