import { useState } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import { id, useConsoleStore } from "../../store";
import type { Disk } from "../../domain";
import { Confirm, Field, formatDateTime as fmt, Metric, Modal, ModalSave, PageHeader, Panel, ResourceTable, StatusBadge } from "../../shared";

export function StoragePage() {
  const { state, mutate } = useConsoleStore(); const [create, setCreate] = useState(false); const [remove, setRemove] = useState<Disk | null>(null); const [query, setQuery] = useState(""); const disks = state.disks.filter((d) => !query || `${d.name}${d.id}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader title="存储管理" description="创建和管理独立云盘，并将云盘挂载到计算实例。" actions={<button className="button primary" onClick={() => setCreate(true)}><Plus size={16} />创建云盘</button>} /><div className="metrics-grid three"><Metric label="云盘总数" value={state.disks.length} detail="当前区域" /><Metric label="总容量" value={`${state.disks.reduce((a, b) => a + b.size, 0)} GiB`} detail="SSD 与 ESSD" /><Metric label="可挂载" value={state.disks.filter((d) => d.status === "available").length} detail="当前未挂载云盘" tone="green" /></div><Panel><div className="filters"><label className="search"><Search size={16} /><input placeholder="搜索云盘名称或 ID" value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="button secondary" onClick={() => setQuery("")}>重置</button></div><ResourceTable heads={["云盘名称 / ID", "类型", "容量", "状态", "挂载实例", "创建时间", "操作"]}>{disks.map((disk) => <tr key={disk.id}><td><strong>{disk.name}</strong><small>{disk.id}</small></td><td>{disk.type}</td><td>{disk.size} GiB</td><td><StatusBadge value={disk.status} /></td><td>{state.instances.find((i) => i.id === disk.instanceId)?.name ?? "-"}</td><td>{fmt(disk.createdAt)}</td><td><div className="row-actions">{disk.status === "available" ? <button className="text-button" disabled={state.instances.length === 0} onClick={() => mutate((s) => ({ ...s, disks: s.disks.map((d) => d.id === disk.id ? { ...d, status: "in-use", instanceId: s.instances[0]?.id } : d) }), "云盘已挂载到首台实例")}>挂载</button> : <button className="text-button" onClick={() => mutate((s) => ({ ...s, disks: s.disks.map((d) => d.id === disk.id ? { ...d, status: "available", instanceId: undefined } : d) }), "云盘已卸载")}>卸载</button>}<button title="删除" onClick={() => setRemove(disk)}><Trash2 size={15} /></button></div></td></tr>)}</ResourceTable></Panel>{create && <DiskModal onClose={() => setCreate(false)} />}{remove && <Confirm title="删除云盘" message={`确定删除“${remove.name}”吗？删除后数据无法恢复。`} onClose={() => setRemove(null)} onConfirm={async () => { const saved = await mutate((s) => ({ ...s, disks: s.disks.filter((d) => d.id !== remove.id) }), "云盘已删除"); if (saved) setRemove(null); }} />}</>;
}
function DiskModal({ onClose }: { onClose: () => void }) { const { mutate } = useConsoleStore(); const [name, setName] = useState(""); const [size, setSize] = useState(100); const [type, setType] = useState<"SSD" | "ESSD">("ESSD"); return <Modal title="创建云盘" onClose={onClose}><div className="form-grid"><Field label="云盘名称"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="云盘类型"><select value={type} onChange={(e) => setType(e.target.value as "SSD" | "ESSD")}><option>ESSD</option><option>SSD</option></select></Field><Field label={`容量 ${size} GiB`}><input type="range" min="20" max="2000" step="20" value={size} onChange={(e) => setSize(Number(e.target.value))} /></Field></div><ModalSave disabled={!name} onClose={onClose} onSave={async () => { const saved = await mutate((s) => ({ ...s, disks: [{ id: id("disk"), name, size, type, status: "available", createdAt: new Date().toISOString() }, ...s.disks] }), "云盘已创建"); if (saved) onClose(); }} /></Modal>; }
